# Site settings
title: "Abhishek Vasudev - iOS Developer"
description: >-
  "This is the personal website and blog of Abhishek Vasudev"

# Multilingual settings
languages: ["en"]  # Add new languages here (e.g., "fr", "de")
default_lang: "en"  # Default language

# Base URL settings
url: "https://www.abhishekvasu.dev"
baseurl: ""

# Permalinks - Clean and SEO-friendly URLs
permalink: "pretty"

# Social links
email: abhishekvasudev7@gmail.com
linkedin_link: 
github_username: 
github_link: 

# Build settings
markdown: kramdown
theme: null 
plugins:
  - jekyll-seo-tag  # Generates SEO meta tags
  - jekyll-sitemap  # Automatically generates sitemap.xml

# Defaults
defaults:
  - scope:
    path: ""
    type: "posts"
    values:
    layout: "post"
  - scope:
    path: ""
    type: "pages"
    values:
    layout: "page"
  - scope:
    path: ""
    type: "travel"
    values:
    layout: "travel"
  - scope:
    path: ""
    type: "links"
    values:
    layout: "link"

# Collections - Portfolio and Blog
collections:
  portfolio:
    output: true
    permalink: "/:collection/:path/"
  posts:
    output: true
    permalink: "/:collection/:year/:month/:day/:title/"