# Site settings
title: Abhishek Vasudev
description: Personal portfolio and blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.abhishekvasu.dev" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives

# Collections
collections:
  travel:
    output: true
    permalink: /travel/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "travel"
    values:
      layout: "travel"

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-category
    tag: archive-tag
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - .github
  - README.md 